name: pricing_calculator
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^14.2.8
  google_fonts: ^6.2.0
  logger: ^2.3.0
  flutter_screenutil: ^5.9.3
  universal_html: ^2.2.4
  visibility_detector: ^0.4.0+2
  firebase_core: ^3.6.0
  flutter_riverpod: ^2.4.9
  freezed_annotation: ^2.4.1
  flutter_fadein: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  build_runner: ^2.4.7

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
